apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-node-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoring
  source:
    repoURL: https://github.com/cnunez19/gitops-testing.git
    targetRevision: main
    path: kubernetes-node-exporter
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true